### ISSUE TITLE
Version Number

### ISSUE THREAD

**Issue by NouCake** [Abstractolotl/azplace-frontend#41]
Improve the State how Version Numbers are handled.
(Display the current Version Number. Maybe use the Github Actions to increase the version number)

**Comment by NouCake** [comment]
@Ancocodet kannst du das in der git pipeline aufnehmen, das jedes mal wenn deployed wird ein **npm version patch** mit ausgeführt wird? (Aber gucken das das nicht die pipeline auch anstößt 😅)

**Comment by Ancocodet** [comment]
@NouCake Kann ich machen, würde aber eventuell vorschlagen, dass über tags dann zu machen.

**Comment by NouCake** [comment]
Pipeline sollte angepasst sein. Nächster Rollout wird abgewartet

**Comment by Ancocodet** [comment]
Tested and is working now.
